[package]
name = "complex-gamma"
version = "0.1.0"
authors = ["dshin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"

[dev-dependencies]
rstest = "0.11.0"
